swagger: '2.0'
info:
  title: Front End API
  description: Api for apply CRUD actions
  version: 1.0.0
basePath: /api/v1
schemes:
  - http
paths:
  /actions/create-job:
    post:
      tags:
        - Actions
      description: It create job and send info to nats topic.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
      responses:
        '200':
          description: Success response
          schema:
            '$ref': '#/definitions/ApiResponse'
        '500':
          description: Error Response
          schema:
            '$ref': '#/definitions/ApiError'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
definitions:
  JobDTO:
    type: object
    required:
      - user
    properties:
      user:
        type: string
    example:
      user: Fernando
  ApiResponse:
    type: object
    properties:
      status:
        type: string
      description:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/JobDTO'
  ApiError:
    type: object
    properties:
      status:
        type: string
      description:
        type: string
