swagger: '2.0'
info:
  title: Front End API
  description: Api for apply CRUD actions
  version: 1.0.0
basePath: /api/v1
schemes:
  - http
paths:
  /actions/create-job:
    post:
      tags:
        - Actions
      description: It create job and send info to nats topic.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: image
          type: file
          description: The file to upload.
      responses:
        '200':
          description: Success response
          schema:
            '$ref': '#/definitions/ApiResponse'
        '500':
          description: Error Response
          schema:
            '$ref': '#/definitions/ApiError'
  /actions/config-observer:
    post:
      tags:
        - Actions
      description: It set parameters for observer.
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - maxSleepTime
              - jobsForWorker
            properties:
              maxSleepTime:
                type: number
              jobsForWorker:
                type: number

      responses:
        '200':
          description: Success response
          schema:
            '$ref': '#/definitions/ApiResponse'
        '500':
          description: Error Response
          schema:
            '$ref': '#/definitions/ApiError'
  /actions/status-job/{id}:
    get:
      tags:
        - Actions
      sumary: Get status job by ID
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: string ID of the job to get
      responses:
        '200':
          description: Success response
          schema:
            '$ref': '#/definitions/ApiResponse'
        '500':
          description: Error Response
          schema:
            '$ref': '#/definitions/ApiError'
  /actions/job-list:
    get:
      tags:
        - Actions
      sumary: Get job list by user
      responses:
        '200':
          description: Success response
          schema:
            '$ref': '#/definitions/ApiResponse'
        '500':
          description: Error Response
          schema:
            '$ref': '#/definitions/ApiError'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
definitions:
  JobDTO:
    type: object
    required:
      - user
    properties:
      user:
        type: string
    example:
      user: Fernando
  ApiResponse:
    type: object
    properties:
      status:
        type: string
      description:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/JobDTO'
  ApiError:
    type: object
    properties:
      status:
        type: string
      description:
        type: string
