version: '3'
services:
  oauth2proxy:
      image: "bitnami/oauth2-proxy:latest"
      container_name: oauth_proxy_container
      ports:
        - 4180:4180
        - 8080:8080
      command: [
        "--provider=github",
        "--cookie-secure=false",
        "--upstream=http://frontend:3000",
        "--http-address=0.0.0.0:8080",
        "--skip-auth-regex=/forms/*",
        "--redirect-url=http://localhost:8080/oauth2/callback",
        "--email-domain=*"
      ]
      restart: always
      env_file:
        - .env
      depends_on:
        - frontend
      networks: 
        - nats
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    restart: on-failure
    links:
      - nats
    environment:
      - NATS_URI=nats://nats:4222
    depends_on:
      - nats
    ports:
      - 3000:3000
    expose:
      - 3000
    networks: 
      - nats
  nats:
    container_name: nats
    image: nats
    hostname: nats-server
    entrypoint: /nats-server
    command: --server_name N1 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats2:4245,nats://nats3:4245 -p 4222
    networks:
      - nats
    ports:
      - 8222:8222
    expose:
      - 4222
  nats2:
    container_name: nats2
    image: nats
    entrypoint: /nats-server
    command: --server_name N2 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats:4245,nats://nats3:4245 -p 4222
    networks:
      - nats
    ports:
      - 4223:4222
  nats3:
    container_name: nats3
    image: nats
    entrypoint: /nats-server
    command: --server_name N3 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats:4245,nats://nats2:4245 -p 4222
    networks:
      - nats
    ports:
      - 4224:4222
networks:
  nats:
    driver: bridge